id = "test-canary-1"

port = 8080
blue_address = "127.0.0.1:2020"
green_address = "127.0.0.1:3030"
max_failures = 3
analysis_interval = "PT3S"

[prometheus]
blue_uri = "http://127.0.0.1:9090"
green_uri = "http://127.0.0.1:9090"
# Both queries calculate the percentage of successful requests
blue_query = "rate(test_backend_success_total{name=\"blue\"}[1m]) / rate(test_backend_total{name=\"blue\"}[1m])"
green_query = "rate(test_backend_success_total{name=\"green\"}[1m]) / rate(test_backend_total{name=\"green\"}[1m])"
# Success rate must be >= 95
min = 95.0

[weight]
start = 0
end = 100
increase = 10
