id = "Test Canary #1"

port = 8080
blue_address = "127.0.0.1:2020"
green_address = "127.0.0.1:3030"
max_failures = 3
analysis_interval = "PT3S"

[prometheus]
blue_query = "TODO - blue"
green_query = "TODO - green"
max = 10

[weight]
start = 0
end = 100
increase = 10
